### PR TITLE
Add cannonical names (iaspec)

### PR DESCRIPTION
**Pull request by lvisintini**
### Definition

- Canonical names are unique across the whole dataset. (we could do away with this if it is problematic down the like, but for the moment it is easily achieved)
- Canonical names only use alphanumerical characters in lower case (no spaces allowed)

- To get a canonical name for a particular component, there are 4 strategies:
    1. Use **elite** and **name** values
    1. Use **elite**, **name** and **game mode** values.
    1. Use **elite**, **name** and **affiliation** values.
    1. Use **elite**, **name** and **description** values.

- If an entry does not have a given value, or that values is `null` or `false`, don't add anything to the canonical name.
- If an entry's value is set to `true`, then add that value's name to the canonical name, except in the case of *elite* (see below)
- If an user has ``entry.elite == true``, only add `'elite'` to the canonical name if  ``entry.unique == false``
- If a entry's value references an array of other elements, only add to the name if that array has only 1 element. Example: (Only add `'skirmish'` or `'campaign'` to the canonical name if `entry.modes.length == 1`)

### Procedure

1. You take all entries that are going to need canonical names (regardless of type) and you define canonical names as an empty string. (just to begin with, we will change)
1. Run the strategies in ascending order and do the following:
    1. You take all the entries that share the same canonical name and use the current strategy to get new canonical names
    1. All the entries that do not have duplicates are taken out of this loop and no longer tampered with.
    1. Go back to step 2.ii using the next strategy.
1. If we continue to have duplicated canonical names, then this specification needs to further adapt to accommodate for the additional edge cases 

I have abstracted this in some code, but it is not the easiest to read at the moment.

### Results
Using the above I'm able to match 93.53% of the canonical names currently in [iaskirmish-data](https://github.com/kingargyle/iaskirmish-data) (340 unique names)

This are the mismatches:

iaspec | proposed | notes
------ | -------- | -----
lukeskywalkerjedi | lukeskywalkerjediknight | Needs renaming to use the description/tag line
lukeskywalker | lukeskywalkerherooftherebellion, lukeskywalkerjediknight | Needs desambiguation
leiaorgana | leiaorganacampaign, leiaorganaskirmish | Needs desambiguation
obiwankenobi | obiwankenobiskirmish, obiwankenobicampaign | Needs desambiguation
r2d2 | r2d2campaign, r2d2skirmish | Needs desambiguation
furyofkashyyk | furyofkashyyyk | There is a typo in iaskirmish-data
atst | eliteatst | Needs to accomodate for the fact that there could be a regular variant
sc2mrepulsortank | elitesc2mrepulsortank | Needs to accomodate for the fact that there could be a regular variant
atdp | eliteatdp | Needs to accomodate for the fact that there could be a regular variant
agentblaise | agentblaisecampaign, agentblaiseskirmish | Needs desambiguation
dewbackrider | elitedewbackrider | Needs to accomodate for the fact that there could be a regular variant
riottrooper | riottroopercampaign, riottrooperskirmish, eliteriottroopercampaign, eliteriottrooperskirmish | Needs desambiguation
crosstraining | elitecrosstraining | Needs to accomodate for the fact that there could be a regular variant
temporaryallianceempire | temporaryalliancemercenary, temporaryallianceimperial | Needs renaming (Imperial deployment, Mercenary deployment, Rebel deployment)
rancor | eliterancorcampaign, eliterancorskirmish | Needs to accomodate for the fact that there could be a regular variant
bantharider | elitebantharider | Needs to accomodate for the fact that there could be a regular variant
bossk | bosskmercenary, bosskrebel | Needs desambiguation
jabbathehutt | jabbathehuttcampaign, jabbathehuttskirmish | Needs desambiguation
elitejawascavenger | jawascavenger, elitejawascavengercampaign, elitejawascavengerskirmish | Needs to accommodate for 3 versions
tempoaryalliancescum | None | There is a typo in iaskirmish-data
feedingfrenzy | elitefeedingfrenzy |  Needs to accomodate for the fact that there could be a regular variant
sarlacsweep | sarlaccsweep | There is a typo in iaskirmish-data

### CODE REVIEW

**Comment by lvisintini** [comment]
This PR addresses issue #11 
@kingargyle, I'm specially interested in your feeback

**Comment by lvisintini** [comment]
```
IASPEC_MAPPING = {
    "lukeskywalkerjedi": "lukeskywalkerjediknight",
    "lukeskywalker": "lukeskywalkerherooftherebellion",
    "leiaorgana": "leiaorganaskirmish",
    "obiwankenobi": "obiwankenobiskirmish",
    "r2d2": "r2d2skirmish",
    "furyofkashyyk": "furyofkashyyyk",
    "atst": "eliteatst",
    "sc2mrepulsortank": "elitesc2mrepulsortank",
    "atdp": "eliteatdp",
    "agentblaise": "agentblaiseskirmish",
    "dewbackrider": "elitedewbackrider",
    "riottrooper": "riottrooperskirmish",
    "crosstraining": "elitecrosstraining",
    "temporaryallianceempire": "temporaryallianceimperial",
    "rancor": "eliterancorskirmish",
    "bantharider": "elitebantharider",
    "bossk": "bosskmercenary",
    "jabbathehutt": "jabbathehuttskirmish",
    "elitejawascavenger": "elitejawascavengerskirmish",
    "tempoaryalliancescum": "temporaryalliancemercenary",
    "feedingfrenzy": "elitefeedingfrenzy",
    "sarlacsweep": "sarlaccsweep",
}
```

**Comment by kingargyle** [comment]
Thanks, been super busy with other stuff, sorry I haven't had a chance to get back.  I'm fine with the proposed changes.

**Comment by kingargyle** [comment]
My original intent with the iaspec was focusing on skirmish, but I'm fine with expanding it beyond that requirement for other use cases.

**Pull request merged**
